services:
    db:
        image: mysql:8
        container_name: products
        restart: always
        environment:
            - MYSQL_DATABASE=products_db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
        ports:
            - 3306:3306
        volumes:
            - ./docs/db/sql/build_database.sql:/docker-entrypoint-initdb.d/build_database.sql
            - ./docs/db/sql/warehouses.sql:/docker-entrypoint-initdb.d/warehouses.sql
            - ./docs/db/sql/test.sql:/docker-entrypoint-initdb.d/test.sql
            - db-data:/var/lib/mysql
volumes:
    db-data: