version: '3.8'
services:
  db:
    image: mysql:8
    container_name: books
    restart: always
    environment:
      - MYSQL_DATABASE=books
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/books.sql
      - db-data:/var/lib/mysql
volumes:
  db-data: